### ISSUE TITLE
CloudEvent response error in kafka broker dispatcher

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/plumbing#1338]
The kafka knative-broker dispatcher logs are full of

```
{
  "@timestamp": "2023-02-03T12:34:12.358Z",
  "@version": "1",
  "message": "Failed to handle subscriber response topic=knative-broker-default-default partition=8 offset=538844",
  "logger_name": "dev.knative.eventing.kafka.broker.dispatcher.impl.RecordDispatcherImpl",
  "thread_name": "vert.x-eventloop-thread-1",
  "level": "ERROR",
  "level_value": 40000,
  "stack_trace": "java.lang.IllegalStateException: Unable to decode response: unknown encoding and non empty response\n\tat dev.knative.eventing.kafka.broker.dispatcher.impl.KafkaResponseHandler.handle(KafkaResponseHandler.java:90)\n\tat dev.knative.eventing.kafka.broker.dispatcher.impl.RecordDispatcherImpl.lambda$composeSenderAndSinkHandler$8(RecordDispatcherImpl.java:201)\n\tat io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)\n\tat io.vertx.core.impl.future.FutureImpl$ListenerArray.onSuccess(FutureImpl.java:262)\n\tat io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)\n\tat io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)\n\tat io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)\n\tat io.vertx.core.Promise.complete(Promise.java:66)\n\tat io.vertx.circuitbreaker.impl.CircuitBreakerImpl.lambda$null$4(CircuitBreakerImpl.java:232)\n\tat io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)\n\tat io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)\n\tat io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Unknown Source)\nCaused by: java.lang.IllegalStateException: Attribute 'type' cannot be null\n\tat io.cloudevents.core.impl.BaseCloudEventBuilder.createMissingAttributeException(BaseCloudEventBuilder.java:208)\n\tat io.cloudevents.core.v1.CloudEventBuilder.build(CloudEventBuilder.java:119)\n\tat io.cloudevents.core.impl.BaseCloudEventBuilder.end(BaseCloudEventBuilder.java:195)\n\tat io.cloudevents.core.impl.BaseCloudEventBuilder.end(BaseCloudEventBuilder.java:36)\n\tat io.cloudevents.core.message.impl.BaseGenericBinaryMessageReaderImpl.read(BaseGenericBinaryMessageReaderImpl.java:72)\n\tat io.cloudevents.core.CloudEventUtils.toEvent(CloudEventUtils.java:91)\n\tat io.cloudevents.core.message.MessageReader.toEvent(MessageReader.java:116)\n\tat io.cloudevents.core.message.MessageReader.toEvent(MessageReader.java:102)\n\tat dev.knative.eventing.kafka.broker.dispatcher.impl.KafkaResponseHandler.handle(KafkaResponseHandler.java:74)\n\t... 18 common frames omitted\n",
  "topic": "knative-broker-default-default",
  "partition": 8,
  "offset": 538844
}
```

The Java stacktrace is:
```
java.lang.IllegalStateException: Unable to decode response: unknown encoding and non empty response
	at dev.knative.eventing.kafka.broker.dispatcher.impl.KafkaResponseHandler.handle(KafkaResponseHandler.java:90)
	at dev.knative.eventing.kafka.broker.dispatcher.impl.RecordDispatcherImpl.lambda(RecordDispatcherImpl.java:201)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
	at io.vertx.core.impl.future.FutureImpl.onSuccess(FutureImpl.java:262)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.Promise.complete(Promise.java:66)
	at io.vertx.circuitbreaker.impl.CircuitBreakerImpl.lambda(CircuitBreakerImpl.java:232)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda-zsh(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Attribute 'type' cannot be null
	at io.cloudevents.core.impl.BaseCloudEventBuilder.createMissingAttributeException(BaseCloudEventBuilder.java:208)
	at io.cloudevents.core.v1.CloudEventBuilder.build(CloudEventBuilder.java:119)
	at io.cloudevents.core.impl.BaseCloudEventBuilder.end(BaseCloudEventBuilder.java:195)
	at io.cloudevents.core.impl.BaseCloudEventBuilder.end(BaseCloudEventBuilder.java:36)
	at io.cloudevents.core.message.impl.BaseGenericBinaryMessageReaderImpl.read(BaseGenericBinaryMessageReaderImpl.java:72)
	at io.cloudevents.core.CloudEventUtils.toEvent(CloudEventUtils.java:91)
	at io.cloudevents.core.message.MessageReader.toEvent(MessageReader.java:116)
	at io.cloudevents.core.message.MessageReader.toEvent(MessageReader.java:102)
	at dev.knative.eventing.kafka.broker.dispatcher.impl.KafkaResponseHandler.handle(KafkaResponseHandler.java:74)
	... 18 common frames omitted
```

Tekton versions:
```
tkn version
Client version: 0.29.0
Chains version: v0.8.0
Pipeline version: v0.44.0
Triggers version: v0.22.1
Dashboard version: v0.32.0
```

k8s version
```
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14-gke.1800", GitCommit:"1eab5b8da4acab130c72aea21eb7ed3e96523ca2", GitTreeState:"clean", BuildDate:"2022-12-07T09:32:46Z", GoVersion:"go1.17.13b7", Compiler:"gc", Platform:"linux/amd64"}
```

knative version
```
  labels:
    app.kubernetes.io/name: eventing-controller
    app.kubernetes.io/part-of: knative-eventing
    app.kubernetes.io/version: 1.0.0
```

Strimzi and kafka versions
```
2023-02-03 08:36:09 INFO  Main:60 - ClusterOperator 0.26.0 is starting
2023-02-03 08:36:10 INFO  Main:62 - Cluster Operator configuration is ClusterOperatorConfig(namespaces=[kafka],reconciliationIntervalMs=120000,operationTimeoutMs=300000,connectBuildTimeoutMs=300000,createClusterRoles=false,networkPolicyGeneration=true,versions=versions{2.8.0={proto: 2.8 msg: 2.8 kafka-image: quay.io/strimzi/kafka:0.26.0-kafka-2.8.0 connect-image: quay.io/strimzi/kafka:0.26.0-kafka-2.8.0 mirrormaker-image: quay.io/strimzi/kafka:0.26.0-kafka-2.8.0 mirrormaker2-image: quay.io/strimzi/kafka:0.26.0-kaf
ka-2.8.0}, 2.8.1={proto: 2.8 msg: 2.8 kafka-image: quay.io/strimzi/kafka:0.26.0-kafka-2.8.1 connect-image: quay.io/strimzi/kafka:0.26.0-kafka-2.8.1 mirrormaker-image: quay.i
o/strimzi/kafka:0.26.0-kafka-2.8.1 mirrormaker2-image: quay.io/strimzi/kafka:0.26.0-kafka-2.8.1}, 3.0.0={proto: 3.0 msg: 3.0 kafka-image: quay.io/strimzi/kafka:0.26.0-kafka-
3.0.0 connect-image: quay.io/strimzi/kafka:0.26.0-kafka-3.0.0 mirrormaker-image: quay.io/strimzi/kafka:0.26.0-kafka-3.0.0 mirrormaker2-image: quay.io/strimzi/kafka:0.26.0-ka
fka-3.0.0}},imagePullPolicy=null,imagePullSecrets=null,operatorNamespace=kafka,operatorNamespaceLabels=null,rbacScope=CLUSTER,customResourceSelector=null,featureGates=Featur
eGates(controlPlaneListener=false,ServiceAccountPatching=false))
```

**Comment by afrittoli** [comment]
Tekton triggers event listeners should respond correctly to CloudEvents after https://github.com/tektoncd/triggers/pull/1469

**Comment by afrittoli** [comment]
> Tekton triggers event listeners should respond correctly to CloudEvents after [tektoncd/triggers#1469](https://github.com/tektoncd/triggers/pull/1469)

Tekton triggers uses the v2 path of the SDK to parse cloudevents which expects `Ce-` type of headers, while events sent by Tekton pipelines use `ce_` type of headers, so the events are not recognised as CloudEvents.

**Comment by afrittoli** [comment]
> ents sent by Tekton pipelines use `ce_` type of headers, so the events are not recognised as CloudEvents. I'm not sure where the "_" comes from actually, digging a bit more.

Tried in my local env, events sent by pipelines use `ce-` headers, so it must be something in the CloudEvents broker that changes the format.

**Comment by afrittoli** [comment]
I now configured the deadlettersink in the broker, to point to the http echo service, and I see all events being sent there:
```
::ffff:10.56.4.152 - - [03/Feb/2023:15:55:21 +0000] "POST / HTTP/1.1" 200 20244 "-" "Vert.x-WebClient/4.2.5"
-----------------
{
    "path": "/",
    "headers": {
        "user-agent": "Vert.x-WebClient/4.2.5",
        "prefer": "reply",
        "ce-specversion": "1.0",
        "ce-id": "89df511e-b7c6-452c-9681-d0e893d9a2d5",
        "ce-source": "/apis///namespaces/tekton-ci//04f2a6d0-a3db-check-pr-has-kind-label-logs-stop-upload-data",
        "ce-type": "dev.tekton.event.taskrun.successful.v1",
        "content-type": "application/json",
        "ce-subject": "04f2a6d0-a3db-check-pr-has-kind-label-logs-stop-upload-data",
        "ce-time": "2023-02-03T15:55:27.448439399Z",
        "ce-knativeerrordest": "http://el-tekton-events.default.svc.cluster.local:8080",
        "content-length": "7452",
        "host": "http-echo.default.svc.cluster.local:8080"
    },
```

**Comment by afrittoli** [comment]
Enabled debug logging in the event listener:

```
and header: map[Ce-Id:[dfdf0922-b44c-4e0f-9bb2-92fc9be92355] Ce-Source:[/apis///namespaces/tekton-ci//705ac050-a409-check-pr-has-kind-label-logs-start-create-data] Ce-Specversion:[1.0] Ce-Subject:[705ac050-a409-check-pr-has-kind-label-logs-start-create-data] Ce-Time:[2023-02-03T21:27:23.95596116Z] Ce-Type:[dev.tekton.event.taskrun.running.v1] Content-Length:[7455] Content-Type:[application/json] Prefer:[reply] User-Agent:[Vert.x-WebClient/4.2.5]]","eventlistener":"tekton-events","namespace":"default","/triggers-eventid":"926e8890-e2d5-4d95-b770-95ab11984c0d","eventlistenerUID":"b37832bb-3e30-4516-9b04-c41d626e9321","/triggers-eventid":"926e8890-e2d5-4d95-b770-95ab11984c0d"}
```
